### ISSUE TITLE
Update codebase to modern Swift style

### ISSUE THREAD

**Issue by ilyakuteev** [open-spaced-repetition/swift-fsrs#1]
For now the codebase uses classes to describe TDO models and uses outdated `NSCopying` mechanics.
The proposal is to use structs instead of classes and to use `Equatable` instead of `NSCopying`

**Comment by bensmiley** [comment]
Feel free to go ahead with these improvements, I'm happy to review the PR.

**Comment by ilyakuteev** [comment]
https://github.com/open-spaced-repetition/swift-fsrs/pull/2
PR link

**Comment by ilyakuteev** [comment]
> Feel free to go ahead with these improvements, I'm happy to review the PR.

Thanks for quick response. I attached a PR link to the issue.

**Comment by bensmiley** [comment]
I merged it. Thanks for cleaning up the code.
