### ISSUE TITLE
Add Package.swift

### ISSUE THREAD

**Issue by ilyakuteev** [open-spaced-repetition/swift-fsrs#3]
The most popular and native way to distribute swift libraries is SPM. To enable package distribution a `Package.swift` file should be added in a repo root. For now it should contain two targets: the main library and tests.

**Comment by ilyakuteev** [comment]
https://github.com/open-spaced-repetition/swift-fsrs/pull/4
PR Link

**Comment by bensmiley** [comment]
Merged
